### ISSUE TITLE
efiling Defendant issue

### ISSUE THREAD

**Issue by colarusso** [SuffolkLITLab/docassemble-EFSPIntegration#83] opened 2021-09-23 02:13 UTC
I was asked if there was a defendant or respondent in a case (screen id: is there an opposing party?) for a case where it had earlier determined that I was the defendant or respondent (screen id: is the user the plaintiff or defendant?). Then when I said there was one, it wanted me to enter in a bunch of info. It then correctly assumed they were the plaintiff/petitioner (screen id: party type of other parties). So, the issue seems to be with the "is there an opposing party?" screen. However, the question "Is there any other defendant or respondent in this matter?" (screen id: any other opposing parties) did come up despite me earlier saying there were no other parties on my side.

**Comment by BryceStevenWilley** [comment] 2021-09-23 04:33
Good catch. Looks like it's because the default value of `al_form_type` is `"starts_case"`, which we shouldn't use. Should be fixed soon.

**Comment by nonprofittechy** [comment] 2021-09-23 16:30
@colarusso if you click the "snapshot" button and copy over the variables into your github issue, it can help reproduce the issue next time. I suggest using "snapshot" instead of show variables and values because it has a little less clutter, but that works too. we should make that workflow easier than it is now, but it should be doable. LMK if you want a quick demo

**Comment by BryceStevenWilley** [comment] 2022-07-27 19:39
Fixed in https://github.com/SuffolkLITLab/docassemble-EFSPIntegration/commit/ef6eb85538aea71ea85923d3348db8aa287a3da1, and is stale for existing cases: we handle other_parties for existing cases differently now.

**Closed by BryceStevenWilley** 2022-07-27 19:39 UTC
Labels: enhancement
